sgs_website/south_garage_website/cards/urls.py
from django.urls import path
from .views import ItemDetailView # , HomeViewб CategoryView ,getCategory, SortByPopularityView

app_name = 'cards' # This is the namespace so you can reverse urls with core:*

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('<slug>/', ItemDetailView.as_view(), name='product'),
    #path('category/<str:slug>/', CategoryView.as_view(), name='category')
    # path("create/", views.TaskCreateView.as_view(), name='create'),
    # path('', views.index, name="index2"),
    # path("list/", views.TaskListView.as_view(), name='list'),
    # path("create/", views.TaskCreateView.as_view(), name='create'),

]

sgs_website/south_garage_website/orders/urls.py
from django.urls import path
from . import views
from .views import ItemDetailView

app_name = "orders"

urlpatterns = [
    path('make-order/', views.make_order, name='make-order'),
    #path('success/', pay_for_order, name='pay_for_order'),
    path('show-paid-orders/', views.show_paid_orders, name='show_paid_orders'),
    path('show-expired-orders/', views.show_expired_orders, name='show_expired_orders'),
    path('show-orders/', views.show_orders, name='show_orders'),
    #path('paymentsss/', views.make_payment, name='make_payment'),
    #path('info/', views.get_info, name='get_info'),
    path('<order_id>/', ItemDetailView.as_view(), name='view_order'),
    #path('sign-up', views.create_user),
    #path('sign-in', views.sign_in),
    #path('logout', views.logout),
    # path('admin/', admin.site.urls),
    # path("create/", views.TaskCreateView.as_view(), name='create'),
    # path('', views.index, name="index2"),
    # path("list/", views.TaskListView.as_view(), name='list'),
    # path("create/", views.TaskCreateView.as_view(), name='create'),
]

sgs_website/south_garage_website/south_garage_website/urls.py
from django.contrib import admin
from django.urls import include, path
from cards.views import HomeView, CategoryView, SortByPopularityView, SortByMaxPriceView, SortByMinPriceView
#from cart.views import view
from cart.views import *
from .views import *
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

app_name = 'core' # This is the namespace so you can reverse urls with core:*

urlpatterns = [
    path('orders/', include('orders.urls', namespace="orders")),


    path('order/<str:order_number>', OrderDetailView.as_view(), name='order'),

    #listarmateriales/<str:tipolista>

    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('popular/', SortByPopularityView.as_view(), name='popular'),
    path('group-by-max-price/', SortByMaxPriceView.as_view(), name='groupbymaxprice'),
    path('group-by-min-price/', SortByMinPriceView.as_view(), name='groupbyminprice'),

    path('product/', include('cards.urls', namespace="cards")),
    path('category/<slug:slug>/', CategoryView.as_view(), name='category'),
    path('contacts', contact, name='contacts'),

    path('cart/', cart_view, name='cart'),
    path('view_order/', view_order, name='view_order'),

    path('add-item-to-cart/<slug:slug>/', add_item_to_cart, name='add_item_to_cart'),
    path('cart_delete_item/<int:pk>/', CartDeleteItem.as_view(), name='cart_delete_item'),
    path('pluscart/', plus_cart),
    path('minuscart/', minus_cart),
    path('removecart/', remove_cart),
    path('update_cart_amount/', manual_update_item_amount_in_the_cart, name='update_cart_amount'),
    path('make_order/', make_order, name='make_order'),
    path('return_order/', return_order, name='return_order'),
    #path('payment/', payment, name='payment'),
    #path('make-a-payment/', pay_for_order, name='make-a-payment'),
    #path('pay/', pay, name='pay'),
    #path('check_payment/', check_payment, name='check_payment'),
    #path('webhook/', webhook),
    path('payments-check/', webhook),
    #path('success/', pay_for_order, name='pay_for_order'),

    # auth
    path('logout/', logout_view, name='logout'),
    path('aboutus/', about_us, name='aboutus'),
    path('sign-in/', signin, name='login'),
    path('sign-up/', signup, name='signup'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('captcha/', include('captcha.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''метод as.view() возвращает функцию, которая может быть вызвана, когда приходит запрос на URL, соответствующий связанному шаблону'''

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

sgs_website/south_garage_website/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from cards.models import Card
from django.contrib.auth import get_user_model #It's not recommended to import the User directly as it won't work in projects where the AUTH_USER_MODEL setting has been changed to a different user model. Use the get_user_model method instead:
from orders.models import Payment
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db.models.signals import post_delete
from django.db.models import Sum
from decimal import Decimal
from django.utils import timezone
from django.utils.timezone import datetime
from django.shortcuts import reverse

User = get_user_model()

class Cart(models.Model):

    STATUS_CART = '1_cart'
    STATUS_WAITING_FOR_PAYMENT = '2_waiting_for_payment'
    STATUS_PAID = '3_paid'
    STATUS_EXPIRED = '4_expired'
    STATUS_CHECK_PAY = '5_check_pay'

    STATUS_CHOICES = [
        (STATUS_CART, 'cart'),
        (STATUS_WAITING_FOR_PAYMENT, 'waiting_for_payment'),
        (STATUS_PAID, 'paid'),
        (STATUS_EXPIRED, 'expired'),
        (STATUS_CHECK_PAY, 'check_pay'),
    ]

    def get_num(date=datetime.now()): # функция для посчета номера заказа (запуск функции в момент создания новой корзины)
        date = date.strftime('%Y%m')[2:6] # получаем текущую дату в нужном нам формате - год, месяц
        if Cart.objects.all().last(): # если есть хоть одна корзина в бд
            last_order = Cart.objects.all().last() # получаем последнюю корзину
            if last_order.order_number[0:4] == date: # проверяем, если год и месяц последнего заказа совпадает с текущими, то
                num = int(last_order.order_number[4::]) + 1 # увеличиваем номер заказа на 1
            else:
                num = 1 # иначе номер заказа начнется с 1
        else:
            return f'{date}1' # если еще нет корзин в базе данных, то присваиваем первому заказу номер 1 с текущей датой
        return(f'{date}{num:04}') # в таком формате функция get_num отдает номер заказа


    order_number = models.CharField(max_length=8, default=get_num, verbose_name='Номер заказа')
    user = models.ForeignKey(User, related_name="cart", on_delete=models.CASCADE, null=True, blank=True, verbose_name='Пользователь')
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, verbose_name='Статус', default=STATUS_CART)
    payment = models.ForeignKey(Payment, on_delete=models.PROTECT, blank=True, null=True)
    total = models.DecimalField(default=0.00, max_digits=25, decimal_places=2, verbose_name='Сумма заказа')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    is_active = models.BooleanField(default=True, verbose_name='Активно')
    is_changed_by_shop = models.BooleanField(default=False, verbose_name='Служебное поле. Корректировка наличия из-за изменения остатка')
    comment = models.TextField(blank=True, null=True)
    delivery_price = models.DecimalField(default=0.00, max_digits=25, decimal_places=2, verbose_name='Стоимость доставки')
    total_with_delivery = models.DecimalField(default=0.00, max_digits=25, decimal_places=2, verbose_name='Итоговая стоимость')
    payment_link = models.CharField(max_length=300, default='null', verbose_name='Платежная ссылка')

    def get_absolute_url(self):
        return reverse("order", kwargs={
           'order_number': self.order_number
        })

    def __unicode__(self):
        return "Id корзины: %s" %(self.id) #
    def __str__(self):
        return f"Корзина: {self.order_number}, её статус {self.status}"
    class Meta:
        verbose_name = 'Корзина'  # verbose это алиас для админки
        verbose_name_plural = 'Корзины'

    @staticmethod
    def get_cart(user: User):
        cart = Cart.objects.filter(user=user, status=Cart.STATUS_CART).first()

        if cart: #and (timezone.now() - cart.created_at.days) > 7: автоматическое удаление корзины после 7 дней бездействия
            pass
            #cart.delete()
            #cart = None

        if not cart:
            cart = Cart.objects.create(user=user, status=Cart.STATUS_CART)
        return cart


    @staticmethod
    def get_order(user: User):
        #print('VOT - ', CartItem.objects.last())
        cart = Cart.objects.filter(user=user, status=Cart.STATUS_WAITING_FOR_PAYMENT).first()

        #dt.timedelta = timezone.now() - cart.created_at
        if cart and (timezone.now() - cart.created_at).days > 1: #автоматическое устаревание неоплаченного заказа после 1 дня бездействия
            print("Заказ просрочен")
            cart = Cart.objects.filter(user=user, status=Cart.STATUS_WAITING_FOR_PAYMENT).update(status=Cart.STATUS_EXPIRED)

        #if not cart:
        #    cart = Cart.objects.create(user=user, status=Cart.STATUS_WAITING_FOR_PAYMENT)
        return cart

    def get_total_price(self):
        total = Decimal(0)
        for item in self.cartitem_set.all(): # с помощью set получаем значения, которые по форейн ки ссылаются на карт
            total += (item.price * item.quantity)
        return total

    @staticmethod
    def get_amount_of_unpaid_orders(owner: User):
        amount = Cart.objects.filter(owner=User, status=Cart.STATUS_WAITING_FOR_PAYMENT).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name='Корзина') # кавычки у Cart были бы нужны, если бы этот класс определен ниже
    card = models.ForeignKey(Card, on_delete=models.PROTECT, verbose_name='Товар')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')
    line_total = models.DecimalField(default=10.00, max_digits=1000, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    price = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    discount = models.DecimalField(max_digits=20, decimal_places=2, default=0)


    def __unicode__(self):
        try:
            return str(self.card.id)
        except:
            return f' {self.card.name} + {self.quantity}'

    def __str__(self):
        return f"{self.cart}, товар {self.card}"

    class Meta:
        verbose_name = 'Товар в корзине'  # verbose это алиас для админки
        verbose_name_plural = 'Товары в корзине'

    @property
    def amount(self): #подсчет суммарной цены для одной позиции
        return self.quantity * ((self.price) - (self.discount))

@receiver(post_save, sender=CartItem) #после сохранения объекта картайтем вызывается функция ниже
def recalculate_cart_amount_after_save(sender, instance, **kwargs):
    cart = instance.cart
    cart.total = cart.get_total_price()
    cart.save()

@receiver(post_delete, sender=CartItem)  # после удаления объекта картайтем вызывается функция ниже
def recalculate_cart_amount_after_delete(sender, instance, **kwargs):
    cart = instance.cart
    cart.total = cart.get_total_price()
    cart.save()

def update_item_amount_in_the_cart(user: User):

    cart = Cart.objects.filter(status=Cart.STATUS_CART, user=user).first()
    #print(cart)
    #print('cart')
    #print('Апдейтик')
    #cart.total = cart.get_total_price()
    items = cart.cartitem_set.all()
    #print('items')
    #print(items)
    for item in items:
        #print('item')
        #print(item)
        #print('СТАРЫЙ item.quantity')
        #print(item.quantity)
        card = Card.objects.get(pk=item.card_id)
        #print('СТАРЫЙ остаток товара card.amount')
        #print(card.amount)
        #print('card.amount - item.quantity')
        #print(card.amount - item.quantity)

        if (card.amount - item.quantity) < 0:
            #print('проверочка запустилась да')
            #print('item.quantity')
            #print(item.quantity)
            item.quantity = card.amount
            item.save()
            #print('item save успешно')
            #print(item.quantity)
            #print('item.quantity=card.amount')
            #print(item.quantity)
            #CartItem.objects.filter(card=card).update(quantity=card.amount)
            #Cart.objects.filter(user=user, status=Cart.STATUS_CART).update(is_changed_by_shop=True)
        #cart.total = cart.get_total_price()
            cart.is_changed_by_shop = True
            cart.total = cart.get_total_price()
            cart.save()
        if item.quantity == 0:
            item.delete()
        cart.save()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # on_delete=models.CASCADE - автоматически удаляет строку из зависимой таблицы, если удаляется связанная строка из главной таблицы
    first_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Имя')
    last_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Фамилия')
    surname = models.CharField(max_length=100, blank=False, null=True, verbose_name='Отчество')
    birth_date = models.DateField(blank=True, null=True, verbose_name='Дата рожджения')
    phone = models.CharField(max_length=100, blank=True, null=True, verbose_name='Номер телефона') # number
    address = models.CharField(max_length=100, blank=True, null=True, verbose_name='Адрес доставки')
    zip_code = models.CharField(max_length=100, blank=True, null=True, verbose_name='Почтовый индекс')
    comment = models.CharField(max_length=1000, blank=False, null=True, verbose_name='Комментарий к заказу')
    delivery_type = models.CharField(max_length=100, blank=True, null=True, verbose_name='Почтовый сервис')
    
    def __str__(self):
        return str(self.user)
    
    class Meta:
        verbose_name = 'Данные о заказе'  # verbose это алиас для админки
        verbose_name_plural = 'Данные о заказе'

sgs_website/south_garage_website/cart/forms.py
from django import forms

from .models import CartItem

class AddQuantityForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ['quantity']

sgs_website/south_garage_website/orders/forms.py
from django import forms
from .models import DeliveryType
from captcha.fields import CaptchaField


class Login_form(forms.Form):
    username = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))

class Register_form(forms.Form):
    username = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField()

class Order_form(forms.Form):
    delivery_type = forms.ModelChoiceField(queryset=DeliveryType.objects.filter(is_active=True).all(), empty_label="Выбрать") # Параметр to_field_name="delivery" обозначет, по какому столбцу таблицы DelyveryType будут отображаться значения в форме
    address = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Москва, ул. Академика Королева, 12'}))
    phone = forms.CharField(max_length=16, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '+7 (123) 456-78-90'}))
    zip_code = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '127427'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Иван'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Иванов'}))
    surname = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Иванович'}))
    comment = forms.CharField(max_length=1000, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Любая дополнительная информация'}))

sgs_website/south_garage_website/templates/contact123.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	
	<!-- Breadcrumbs -->
	<div class="breadcrumbs">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="bread-inner">
						<ul class="bread-list">
							<li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
							<li class="active"><a href="blog-single.html">Contact</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Breadcrumbs -->
  
	<!-- Start Contact -->
	<section id="contact-us" class="contact-us section">
		<div class="container">
				<div class="contact-head">
					<div class="row">
						<div class="col-lg-8 col-12">
							<div class="form-main">
								<div class="title">
									<h4>Get in touch</h4>
									<h3>Write us a message</h3>
								</div>
								<form class="form" method="post" action="../south_garage_website/static/mail/mail.php">
									<div class="row">
										<div class="col-lg-6 col-12">
											<div class="form-group">
												<label>Your Name<span>*</span></label>
												<input name="name" type="text" placeholder="">
											</div>
										</div>
										<div class="col-lg-6 col-12">
											<div class="form-group">
												<label>Your Subjects<span>*</span></label>
												<input name="subject" type="text" placeholder="">
											</div>
										</div>
										<div class="col-lg-6 col-12">
											<div class="form-group">
												<label>Your Email<span>*</span></label>
												<input name="email" type="email" placeholder="">
											</div>	
										</div>
										<div class="col-lg-6 col-12">
											<div class="form-group">
												<label>Your Phone<span>*</span></label>
												<input name="company_name" type="text" placeholder="">
											</div>	
										</div>
										<div class="col-12">
											<div class="form-group message">
												<label>your message<span>*</span></label>
												<textarea name="message" placeholder=""></textarea>
											</div>
										</div>
										<div class="col-12">
											<div class="form-group button">
												<button type="submit" class="btn ">Send Message</button>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
						<div class="col-lg-4 col-12">
							<div class="single-head">
								<div class="single-info">
									<i class="fa fa-phone"></i>
									<h4 class="title">Call us Now:</h4>
									<ul>
										<li>+123 456-789-1120</li>
										<li>+522 672-452-1120</li>
									</ul>
								</div>
								<div class="single-info">
									<i class="fa fa-envelope-open"></i>
									<h4 class="title">Email:</h4>
									<ul>
										<li><a href="mailto:info@yourwebsite.com">info@yourwebsite.com</a></li>
										<li><a href="mailto:info@yourwebsite.com">support@yourwebsite.com</a></li>
									</ul>
								</div>
								<div class="single-info">
									<i class="fa fa-location-arrow"></i>
									<h4 class="title">Our Address:</h4>
									<ul>
										<li>KA-62/1, Travel Agency, 45 Grand Central Terminal, New York.</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
	</section>
	<!--/ End Contact -->

{% endblock %}

sgs_website/south_garage_website/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

    <!-- ...:::: Start Breadcrumb Section:::... -->
    <div class="breadcrumb-section breadcrumb-bg-color--golden">
        <div class="breadcrumb-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h3 class="breadcrumb-title">Товары в наличии</h3>
                        <div class="breadcrumb-nav breadcrumb-nav-color--black breadcrumb-nav-hover-color--golden">
                            <nav aria-label="breadcrumb">
                                <ul>
                                    <li class="active"><a href="{% url 'home' %}">Главная</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- ...:::: End Breadcrumb Section:::... -->

    <!-- ...:::: Start Shop Section:::... -->
    <div class="shop-section">
        <div class="container">
            <div class="row flex-column-reverse flex-lg-row">
                <div class="col-lg-12">
                    <!-- Start Shop Product Sorting Section -->
                    <div class="shop-sort-section">
                        <div class="container">
                            <div class="row">
                                <!-- Start Sort Wrapper Box -->
                                <div class="sort-box d-flex justify-content-between align-items-md-center align-items-start flex-md-row flex-column"
                                    data-aos="fade-up" data-aos-delay="0">
                                    <!-- Start Sort tab Button -->
                                    <div class="sort-tablist d-flex align-items-center">
                                        <!-- Start Page Amount -->
                                        <div class="page-amount ml-2">
                                            <span>Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
                                        </div> <!-- End Page Amount -->
                                    </div> <!-- End Sort tab Button -->

                                    <!-- Start Sort Select Option -->
                                    <div class="sort-select-list d-flex align-items-center">
                                        <label class="mr-2">Сортировка по:</label>
                                        <form action="#">
                                            <fieldset>
                                                <select name="speed" id="speed" onchange="location = this.value;">
                                                    <option value="{% url 'home' %} selected=selected">от А до Я</option>
                                                    <option value="{% url 'popular' %}"> по популярности </option>
                                                    <option value="{% url 'groupbymaxprice' %}">сначала дешевые</option>
                                                    <option value="{% url 'groupbyminprice' %}">сначала дорогие</option>
                                                </select>
                                            </fieldset>
                                        </form>
                                    </div> <!-- End Sort Select Option -->
                                </div> <!-- Start Sort Wrapper Box -->
                            </div>
                        </div>
                    </div> <!-- End Section Content -->

                    <!-- Start Tab Wrapper -->
                    <div class="sort-product-tab-wrapper">
                        <div class="container">
                            <div class="row">
                                <div class="col-12">
                                    <div class="tab-content">
                                        <!-- Start Grid View Product -->
                                        <div class="tab-pane active show sort-layout-single" id="layout-4-grid">
                                            <div class="row">
                                                {% for card in object_list %}
                                                <div class="col-xl-3 col-lg-4 col-sm-6 col-12">
                                                <form method="post" action="{% url 'add_item_to_cart' card.slug %}">
                                                    <!-- Start Product Default Single Item -->
                                                    <div class="product-default-single-item product-color--golden"
                                                        data-aos="fade-up" data-aos-delay="0">
                                                        <div class="image-box">

                                                            <a href="{{ card.get_absolute_url }}" class="image-link">
                                                                {% thumbnail card.images.first.img "200x200" crop="center" as im %}
                                                                    <img src="{{ im.url }}">
                                                                {% empty %}
                                                                    <p>No image</p>
                                                                {% endthumbnail %}
                                                            </a>
                                                            {% csrf_token %}

                                                        </div>
                                                        <div class="content">
                                                            <div class="content-left">
                                                                <h6 class="title"><a href="{{ card.get_absolute_url }}">{{ card.name }}</a></h6>
                                                                <ul class="review-star">
                                                                    <input hidden="hidden" type="number" name="quantity" value="1" min="1" max="{{ card.amount }}" required id="id_quantity"/>
                                                                    <button type="submit">В корзину <i class="icon-check"></i></button>
                                                                    <li class="fill"><i class="ion-android-star"></i>
                                                                    </li>
                                                                    <li class="fill"><i class="ion-android-star"></i>
                                                                    </li>
                                                                    <li class="fill"><i class="ion-android-star"></i>
                                                                    </li>
                                                                    <li class="fill"><i class="ion-android-star"></i>
                                                                    </li>
                                                                    <li class="empty"><i class="ion-android-star"></i>
                                                                    </li>
                                                                    <li class="empty"><i>{{ card.amount }}</i>
                                                                    </li>
                                                                </ul>
                                                            </div>
                                                            <div class="content-right">
                                                                <span class="price">{{ card.new_price }}₽</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>

                                                    <!-- End Product Default Single Item -->
                                                </div>
                                                {% endfor %}
                                                </div>
                                            </div>
                                        </div> <!-- End Grid View Product -->

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> <!-- End Tab Wrapper -->

                    <!-- Start Pagination -->
                    <div class="page-pagination text-center" data-aos="fade-up" data-aos-delay="0">
                        <ul>
                            {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                            <li><a class="active">{{ page_obj.number }}</a></li>
                            {% endif %}
                            {% if page_obj.has_next %}
                            <li><a class="active">{{ page_obj.number }}</a></li>
                            <li><a href="?page= {{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                            {% endif %}
                            {% if page_obj.paginator.num_pages > 2 %}
                            <li><a href="?page={{ page_obj.paginator.num_pages }}"><i class="ion-ios-skipforward"></i></a></li>
                            {% endif %}
                        </ul>
                    </div> <!-- End Pagination -->

                </div> <!-- End Shop Product Sorting Section  -->

                </div> <!-- End Shop Product Sorting Section  -->
            </div>
        </div>
    </div> <!-- ...:::: End Shop Section:::... -->


































































{% endblock %}

sgs_website/south_garage_website/templates/repeated-email.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<!-- Start Checkout -->
		<section class="shop checkout section">
			<div class="container">
				<div class="row">
					<br class="col-lg-8 col-12">

                        <h3>Создание новой учетной записи</h3>
                        </br>>
                        <h4>Ошибочка. Такой логин уже зарегистрирован! Вы можете <a href="{% url 'password_reset' %}">восстановить пароль</a> или <a href="{% url 'signup' %}">выбрать другой логин</a>.</h4>
					</div>
				</div>
			</div>
		</section>
		<!--/ End Checkout -->

{% endblock %}